name: Build EventAPI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build EventAPI
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.disembark.dev
          username: robot$deploy-7tv
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          endpoint: builders

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "BUILDER=${{ github.actor }}"
            "VERSION=${{ github.sha }}"
          tags: |
            harbor.disembark.dev/7tv/event-api:${{ github.sha }}
            harbor.disembark.dev/7tv/event-api:latest

  deploy:
    name: Deploy (Production)
    runs-on: ubuntu-latest
    needs: # Run this after build
      - build

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Deploy to k8s
      - name: Install kubectl&
        uses: azure/setup-kubectl@v2.1

      - name: Apply Deployment & Rollout
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
          KUBE_RESOURCE: deploy
          KUBE_IMAGE_PATCH: >-
            [
              { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "harbor.disembark.dev/7tv/event-api:${{ github.sha }}" }
            ]
        run: |
          mkdir -p ~/.kube
          (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
          kubectl config use-context autodeploy@SevenTV

          kubectl patch -n app $KUBE_RESOURCE seventv-events --type="json" -p="$KUBE_IMAGE_PATCH"
