name: Build & Deploy (Production)

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build (Production)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Authenticate with the registry
      - name: Log into Harbor Registry
        uses: docker/login-action@v1 
        with:
          registry: harbor.disembark.dev
          username: robot$deploy-7tv
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      # Build image
      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            harbor.disembark.dev/7tv/eventapi:${{ github.sha }}
            harbor.disembark.dev/7tv/eventapi:latest

  deploy:
    name: Deploy (Production)
    runs-on: ubuntu-latest
    needs: # Run this after build
      - build

    steps:
        # Checkout repository
        - uses: actions/checkout@v2

        # Clone k8s repository
        - uses: actions/checkout@v2
          with:
            repository: SevenTV/k8s
            path: k8s
            token: ${{ secrets.SERVICE_PAT }}

        # Deploy to k8s
        - name: Install kubectl&
          uses: azure/setup-kubectl@v1

        - name: Apply Deployment & Rollout
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
            KUBE_RESOURCE: deploy
            KUBE_IMAGE_PATCH: >-
              [
                { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "harbor.disembark.dev/7tv/eventapi:${{ github.sha }}" }
              ]
          run: |
            mkdir -p ~/.kube
            (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
            kubectl config use-context autodeploy@SevenTV

            kubectl apply -f k8s/cluster/7tv/events.yaml
            kubectl patch $KUBE_RESOURCE seventv-events --type="json" -p="$KUBE_IMAGE_PATCH"

            kubectl rollout restart -n app $KUBE_RESOURCE/seventv-events
